### ISSUE TITLE
What about a NuGet package?

### ISSUE THREAD

**Issue by nesk** [OVRTools/OVRSharp#1]
Hi!

Thank you for creating OVRSharp, it's awesome to be able to use OpenVR overlays with a beautiful API like that one. Are you considering to create a NuGet package for it?

**Comment by tjhorner** [comment]
Hey, I'm glad you find this library useful!

Sure, I can definitely upload a NuGet package. I never really thought anyone other than myself and a couple of friends would use this so I never bothered making one lol.

I just published it to NuGet; it should appear once it's done indexing: https://www.nuget.org/packages/OVRSharp/1.0.0

If you don't mind me asking, what are you using the library for?

**Comment by nesk** [comment]
Thank you so much! It will be way easier to use. 🙏

> If you don't mind me asking, what are you using the library for?

I don't mind at all, I'm trying to create some apps to notify the user in VR about messages he have received on various chat platforms. And overlays are just perfect for this use case. 🙂
